### ISSUE TITLE
Projection/TPC issue: MatchError substring(input_1#6269, 1, 2) (Query 22)

### ISSUE THREAD

**Issue by wgip** [XpressAI/SparkCyclone#350]
```
Query 22 *** FAILED ***
(Hide Details)
Message:	substring(input_1#6269, 1, 2) AS cntrycode#6518 (of class org.apache.spark.sql.catalyst.expressions.Alias)
Exception:	scala.MatchError
com.nec.spark.agile.SparkExpressionToCExpression$.evalString(SparkExpressionToCExpression.scala:161)
com.nec.spark.planning.VERewriteStrategy.$anonfun$apply$2(VERewriteStrategy.scala:134)

```

**Comment by BrainyGuyOrg** [comment]
https://www.sparkcyclone.io/tpc-html/20211123160932/

```
com.nec.spark.agile.SparkExpressionToCExpression$.evalString(SparkExpressionToCExpression.scala:161)
com.nec.spark.planning.VERewriteStrategy.$anonfun$apply$2(VERewriteStrategy.scala:134)
scala.collection.immutable.List.map(List.scala:286)
com.nec.spark.planning.VERewriteStrategy.res$1(VERewriteStrategy.scala:131)
com.nec.spark.planning.VERewriteStrategy.apply(VERewriteStrategy.scala:386)
org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)
```

**Comment by BrainyGuyOrg** [comment]
`// /home/carlos/Documents/Development/SparkCyclone/src/main/scala/com/nec/spark/agile/SparkExpressionToCExpression.scala(143)           
case _ => sys.error(s"Could not handle the expression ${expression}, type ${expression.getClass}")                                      
`

**Comment by BrainyGuyOrg** [comment]
tests/tpchbench/src/main/scala/sparkcyclone/tpch/TPCHBenchmark.scala(1161)

**Comment by BrainyGuyOrg** [comment]
SparkCyclone - new GitHub branch
carlos-gh350-add-match-else

**Comment by BrainyGuyOrg** [comment]
```
      case _ => sys.error(s"SparkExpressionToCExpression.evalString: " +
        "Could not match ${expression}, " +
        "class ${expression.getClass}")
```

**Comment by BrainyGuyOrg** [comment]
https://github.com/XpressAI/SparkCyclone/pull/441

**Comment by BrainyGuyOrg** [comment]
`Failed toString() invocation on an object of type [org.apache.spark.sql.execution.QueryExecution]`

**Comment by BrainyGuyOrg** [comment]
```
java.lang.RuntimeException: SparkExpressionToCExpression.evalString: Could not match Success(substring(input_1#57879, 1, 2) AS cntrycode
       │ #59510), class class org.apache.spark.sql.catalyst.expressions.Alias
```

**Comment by BrainyGuyOrg** [comment]
```
  case _ => sys.error(s"SparkExpressionToCExpression.evalString: " +
    s"Could not match ${Try(expression.toString)}, " +
    s"type ${expression.getClass}")
```

**Comment by BrainyGuyOrg** [comment]
```
class Alias
   child: Expression
   name: String
override def toString: String = s"$child AS $name#${exprId.id}$typeSuffix$delaySuffix"

```

**Comment by BrainyGuyOrg** [comment]
new branch
carlos-gh350-query22

**Comment by BrainyGuyOrg** [comment]
```
SLF4J: Failed toString() invocation on an object of type [org.apache.spark.sql.execution.QueryExecution]
   │ Reported exception:
   │ java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.AttributeReference cannot be cast to org.apache.spark.unsafe.typ
   │ es.UTF8String
   │    at org.apache.spark.sql.catalyst.expressions.Substring.nullSafeEval(stringExpressions.scala:1728)
   │    at com.nec.spark.agile.SparkExpressionToCExpression$.evalString(SparkExpressionToCExpression.scala:173)
```

**Comment by BrainyGuyOrg** [comment]
carlos-gh350-query22-2

**Comment by BrainyGuyOrg** [comment]
carlos-gh350-query22-3

**Comment by BrainyGuyOrg** [comment]
```
 SLF4J: Failed toString() invocation on an object of type [org.apache.spark.sql.execution.QueryExecution]
 Reported exception:
 java.lang.RuntimeException: Could not map substring(input_4#57879, 1, 2) IN (13,31,23,29,30,18,17) (class org.apache.spark.sql.catalyst.
       │ expressions.In None); input is List(c_custkey#57875L, c_name#57876, c_address#57877, c_nationkey#57878L, c_phone#57879, c_acctbal#57880, c_mktsegment#57881, c_commen
       │ t#57882), condition is (substring(c_phone#57879, 1, 2) IN (13,31,23,29,30,18,17) AND (c_acctbal#57880 > scalar-subquery#59508 []))
at scala.sys.package$.error(package.scala:30)
at com.nec.spark.planning.VERewriteStrategy.$anonfun$apply$19(VERewriteStrategy.scala:305)
at scala.util.Either.fold(Either.scala:192)
at com.nec.spark.planning.VERewriteStrategy.res$1(VERewriteStrategy.scala:307)
at com.nec.spark.planning.VERewriteStrategy.apply(VERewriteStrategy.scala:692)
```
